### ISSUE TITLE
handle decryption first class via manifests (pubkeys + callback config)

### ISSUE THREAD

**Issue by ampetz** [ku-sldg/am-cakeml#38]
At the moment, decryption is implemented ad-hoc:  `decrypt_bs_to_rawev` in stubs/Appraisal_IO_Stubs.sml is invoked directly by the generalized Copland appraisal procedure.  

This should be more principled:  configure a decryption callback via the manifest compiler toolchain (using existing fields, or adding a new field for use by appraisal).

**Comment by Durbatuluk1701** [comment]
Closing as it will be completed by ku-sldg/attestation-testbed#2
