### ISSUE TITLE
make targets do not match apps directory content

### ISSUE THREAD

**Issue by komp** [ku-sldg/am-cakeml#49]
The README.md file suggests
>> To build another target, type `make <target>`. Refer to the `apps` directory for the full list of targets.
AttestationManager/	ManifestGenerator/	TermToJson/
but the actual targets are lower case and use "_"
e.g. term_to_json

**Comment by Durbatuluk1701** [comment]
As part of this issue we will also be fixing the following:
- Build targets require many more files than are needed to actually build the target
